# Generated by Django 4.2.6 on 2023-10-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JNCDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='檢測設備項目(EX: 水尺、溶氧)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
            ],
            options={
                'verbose_name': '監測設備列表',
                'verbose_name_plural': '監測設備管理',
                'db_table': 'jnc_device',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JNCPositionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=255, verbose_name='設備名稱')),
                ('JNCDevice', models.CharField(max_length=255, verbose_name='設備項目(I6_Web、Feeder、Weather_Station、CloudBox、VirtualDevice)')),
                ('GPSx', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='經度(Longitude)')),
                ('GPSy', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='緯度(Latitude)')),
                ('Connect', models.BooleanField(verbose_name='有無連線')),
                ('USB', models.IntegerField(verbose_name='(-1、0、2、3)')),
                ('SIM', models.IntegerField(verbose_name='(-1、0、4、10)')),
                ('device_url', models.TextField(verbose_name='設備API url')),
                ('inspect_url', models.TextField(verbose_name='檢測API url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
            ],
            options={
                'verbose_name': '監測場域列表',
                'verbose_name_plural': '監測場域管理',
                'db_table': 'jnc_position',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JNCInspectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChType', models.CharField(max_length=50, verbose_name='Channel類型 (AI、DO、DI、VO)')),
                ('TagName', models.CharField(max_length=255, verbose_name='')),
                ('Unit', models.CharField(default=None, max_length=50, verbose_name='單位')),
                ('IsEnable', models.BooleanField(verbose_name='有無啟動')),
                ('Value', models.FloatField(verbose_name='檢測數值結果')),
                ('AlarmState', models.CharField(max_length=50, verbose_name='警告狀態(Discon、Normal、LO)')),
                ('IsRead', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('device_id', models.ForeignKey(db_column='device_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspects', to='devices_inspect.jncdevicemodel')),
                ('position_id', models.ForeignKey(db_column='position_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspects', to='devices_inspect.jncpositionmodel')),
            ],
            options={
                'verbose_name': '檢測數據列表',
                'verbose_name_plural': '檢測數據管理',
                'db_table': 'jnc_inspect',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JNCInspectHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(default=None, max_length=50, verbose_name='單位')),
                ('IsEnable', models.BooleanField(verbose_name='有無啟動')),
                ('Value', models.FloatField(verbose_name='檢測數值結果')),
                ('AlarmState', models.CharField(max_length=50, verbose_name='警告狀態(Discon、Normal、LO)')),
                ('IsRead', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('inspect_id', models.ForeignKey(db_column='inspect_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historys', to='devices_inspect.jncinspectmodel')),
            ],
            options={
                'verbose_name': '歷史檢測數據列表',
                'verbose_name_plural': '歷史檢測數據管理',
                'db_table': 'jnc_inspect_history',
                'ordering': ('created_at',),
            },
        ),
    ]
