# Generated by Django 4.2.5 on 2023-10-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices_inspect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jncdevicemodel',
            table='jnc_device',
        ),
        migrations.CreateModel(
            name='JNCInspectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChType', models.CharField(max_length=50, verbose_name='Channel類型 (AI、DO、DI、VO)')),
                ('TagName', models.CharField(max_length=255, verbose_name='')),
                ('Unit', models.CharField(default=None, max_length=50, verbose_name='單位')),
                ('IsEnable', models.BooleanField(verbose_name='有無啟動')),
                ('Value', models.FloatField(verbose_name='檢測數值結果')),
                ('AlarmState', models.CharField(max_length=50, verbose_name='警告狀態(Discon、Normal、LO)')),
                ('IsRead', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('device_id', models.ForeignKey(db_column='device_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspects', to='devices_inspect.jncdevicemodel')),
            ],
            options={
                'verbose_name': '檢測數據列表',
                'verbose_name_plural': '檢測數據管理',
                'db_table': 'jnc_inspect',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='JNCInspectHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(default=None, max_length=50, verbose_name='單位')),
                ('IsEnable', models.BooleanField(verbose_name='有無啟動')),
                ('Value', models.FloatField(verbose_name='檢測數值結果')),
                ('AlarmState', models.CharField(max_length=50, verbose_name='警告狀態(Discon、Normal、LO)')),
                ('IsRead', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('inspect_id', models.ForeignKey(db_column='inspect_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historys', to='devices_inspect.jncinspectmodel')),
            ],
            options={
                'verbose_name': '歷史檢測數據列表',
                'verbose_name_plural': '歷史檢測數據管理',
                'db_table': 'jnc_inspect_history',
                'ordering': ('created_at',),
            },
        ),
    ]
