# Generated by Django 4.2.6 on 2023-11-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
            ],
            options={
                'db_table': 'authors',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Token使用的場')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('author_id', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='system_app.author')),
            ],
            options={
                'db_table': 'books',
                'ordering': ('created_at',),
            },
        ),
    ]
