# Generated by Django 4.2.6 on 2023-10-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices_inspect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='群組名稱')),
                ('ClientID', models.CharField(max_length=255, verbose_name='Notify設備ID')),
                ('CallBackURL', models.TextField(verbose_name='回調回來的URL')),
                ('ClientSecret', models.TextField(max_length=255, verbose_name='Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
            ],
            options={
                'verbose_name': '推播設備群組',
                'verbose_name_plural': '推播設備群組管理',
                'db_table': 'notify_device',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotifyEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='事件名稱')),
                ('message', models.TextField(verbose_name='事件訊息通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('device_id', models.ForeignKey(db_column='device_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notify.notifydevicemodel')),
            ],
            options={
                'verbose_name': '推播事件',
                'verbose_name_plural': '推播事件管理',
                'db_table': 'notify_event',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotifyTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Token使用的場')),
                ('token', models.TextField(verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
            ],
            options={
                'verbose_name': '推播權杖儲存',
                'verbose_name_plural': '推播權杖儲存管理',
                'db_table': 'notify_token',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='lte、gte、lt、gt、equal、like')),
                ('name', models.CharField(max_length=255, verbose_name='大於等於、小於等於、大於、等於...')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
            ],
            options={
                'verbose_name': '條件列表',
                'verbose_name_plural': '條件列表管理',
                'db_table': 'statement',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotifyStatementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='事件名稱')),
                ('statement', models.TextField(verbose_name='條件定義(依照『;』分號區隔多個條件式-AND)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('event_id', models.ForeignKey(db_column='event_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='notify.notifyeventmodel')),
                ('jnc_inspect_id', models.OneToOneField(db_column='jnc_inspect_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_statement', to='devices_inspect.jncinspectmodel')),
                ('statement_id', models.ForeignKey(db_column='statement_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_statement', to='notify.statement')),
            ],
            options={
                'verbose_name': '推播事件條件',
                'verbose_name_plural': '推播事件條件管理',
                'db_table': 'notify_statement',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='notifydevicemodel',
            name='token_id',
            field=models.ForeignKey(db_column='token_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='notify.notifytokenmodel'),
        ),
        migrations.CreateModel(
            name='AlertLogModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='<日期字串縮減>_<事件ID>')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('event_id', models.ForeignKey(db_column='event_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='notify.notifyeventmodel')),
            ],
            options={
                'verbose_name': '推播警告紀錄',
                'verbose_name_plural': '推播警告紀錄管理',
                'db_table': 'alert_log',
                'ordering': ('created_at',),
            },
        ),
    ]
